# Generated by Django 3.1.4 on 2020-12-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0002_auto_20201217_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='create_date',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='update_date',
            new_name='updateDate',
        ),
    ]
